/* Correctly-rounded complementary error function of binary32 value.

Copyright (c) 2022 Paul Zimmermann, INRIA.

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <math.h> /* for ldexp */

#define SAMPLE 16

/* For 0 <= i < THRESHOLD, P[i] is a degree-8 polynomial approximating erf(x)
   on [i/SAMPLE,(i+1)/SAMPLE], generated by gen_P(8,0.0625) from erfc.sage.
   For THRESHOLD <= i < PSIZE, P[i] approximates erfc(x) on the same range.
   The numbers in comment at the end of each line are the index i and
   the relative accuracy of the minimax polynomial generated by Sollya
   (in terms of bits). */
#define PSIZE 96
#define THRESHOLD 25
static const double P[PSIZE][9] = {
  { 0x0p+0, 0x1.20dd750429b6dp+0, 0x1.1a1fa038de73fp-44, -0x1.812746b09d739p-2, 0x1.a74e2007e4ad5p-29, 0x1.ce2eec8e04e99p-4, 0x1.cb02ed79ae069p-18, -0x1.ba50a1c8a8c66p-6, 0x1.53ba5079f10cap-10 }, /* 0:54.681 */
  { 0x1.17522e7161c8ep-39, 0x1.20dd750349b0cp+0, 0x1.3d1d29c38f2d2p-27, -0x1.812756f01cc35p-2, 0x1.102eabdcd0f6p-18, 0x1.cdfff30e339d3p-4, 0x1.5aec79e9f632dp-12, -0x1.d1ae1fa130cadp-6, 0x1.177cf09d8294bp-8 }, /* 1:57.409 */
  { 0x1.d770ff9e6ab3cp-33, 0x1.20dd74cdaa079p+0, 0x1.65d62b05993fbp-22, -0x1.81289ce96a985p-2, 0x1.a487bc9d58f4cp-15, 0x1.ccd6871a0c1f9p-4, 0x1.79400df4d7666p-10, -0x1.fae4e5e8a169cp-6, 0x1.be094c6813327p-8 }, /* 2:58.389 */
  { 0x1.05c54d2412c58p-28, 0x1.20dd7254519fap+0, 0x1.9201984735bcfp-19, -0x1.812fdb389a1e4p-2, 0x1.e3990dd283729p-13, 0x1.c9b9f408d312fp-4, 0x1.c483a994a4e0cp-9, -0x1.169ccca042847p-5, 0x1.22b9dd3d479dp-7 }, /* 3:59.254 */
  { 0x1.cf14f0538be5ap-26, 0x1.20dd66214dda2p+0, 0x1.b51ed49aa9444p-17, -0x1.8144abda53798p-2, 0x1.47ac16515889cp-11, 0x1.c491e843dbb9ap-4, 0x1.878b45cf90cap-8, -0x1.2e5d85168ffp-5, 0x1.52b7603448aaap-7 }, /* 4:60.259 */
  { 0x1.959dc6ccdab3ap-24, 0x1.20dd493858436p+0, 0x1.0f2dd5711a1dbp-15, -0x1.816522f7ae1f4p-2, 0x1.26621c73eb1e3p-10, 0x1.bf4e80a4d6c3ap-4, 0x1.07dac904839c8p-7, -0x1.3e21e8aee84bfp-5, 0x1.6c579ac750449p-7 }, /* 5:61.935 */
  { 0x1.903809630b906p-24, 0x1.20dd485bfcdf8p+0, 0x1.194cb8c05465dp-15, -0x1.8167d7702b40bp-2, 0x1.32ce7ad45fb3ap-10, 0x1.bec739b84c959p-4, 0x1.0eb8def355296p-7, -0x1.3fad8c5accf43p-5, 0x1.6eb95e6d8419fp-7 }, /* 6:62.775 */
  { -0x1.c1ffc82e40859p-21, 0x1.20de6067f974ep+0, -0x1.98dc27d77cb35p-14, -0x1.80cda511544d5p-2, -0x1.f962e319d4541p-12, 0x1.caf597336866fp-4, 0x1.41f5ab9a230e1p-8, -0x1.2e0091e26acf1p-5, 0x1.5ac59a499e173p-7 }, /* 7:61.22 */
  { -0x1.8b3ce2c76cce8p-18, 0x1.20e39cf73f331p+0, -0x1.554c4f8722b69p-11, -0x1.7e8ec3bc20921p-2, -0x1.83d3c8036c60ep-8, 0x1.ee509f0d3be05p-4, -0x1.e00e8820090dfp-9, -0x1.06151e980f24ep-5, 0x1.3308588f3288bp-7 }, /* 8:60.699 */
  { -0x1.8be17e78be477p-16, 0x1.20f3fd5ab91c9p+0, -0x1.1fb47d5c751dep-9, -0x1.78f87c79acdaep-2, -0x1.268a27bde7daep-6, 0x1.1a1f7270a43ecp-3, -0x1.33b7233f74a14p-6, -0x1.8eb708060887ep-6, 0x1.f6ca53c17216fp-8 }, /* 9:60.474 */
  { -0x1.2f0e94706329cp-14, 0x1.211c94787f9a8p+0, -0x1.720a3d20ebf54p-8, -0x1.6db5a5cc1ceb9p-2, -0x1.46cbce0b73649p-5, 0x1.5366cf5f9b77ap-3, -0x1.50bafa938e8e2p-5, -0x1.cf93569295709p-7, 0x1.71600644e4177p-8 }, /* 10:60.4 */
  { -0x1.8311b38892cbap-13, 0x1.2171e18e65146p+0, -0x1.91614b39f785cp-7, -0x1.5a1979c1c5884p-2, -0x1.31aaa4f9dff37p-4, 0x1.a604bc52f3ba3p-3, -0x1.205f828f040afp-4, -0x1.039e905eb2fbdp-9, 0x1.c0e05909eb39dp-9 }, /* 11:60.434 */
  { -0x1.adadf51bd571fp-12, 0x1.220ed735780e5p+0, -0x1.7f58b040ce227p-6, -0x1.3bb83f30bcde5p-2, -0x1.fbdfb30c59252p-4, 0x1.08dead7d56356p-2, -0x1.afe7afa265fbfp-4, 0x1.746ffd5a33e5ep-7, 0x1.3a794ed0fa395p-10 }, /* 12:60.558 */
  { -0x1.a810ec5537f2dp-11, 0x1.230fcea9e25e3p+0, -0x1.49cd82d65b393p-5, -0x1.114639510b7b9p-2, -0x1.806afe9d81b91p-3, 0x1.4912b7e5a470fp-2, -0x1.26f654d211058p-3, 0x1.988ca4370a30bp-6, -0x1.d258177b8251cp-11 }, /* 13:60.769 */
#if 0
  { -0x1.78d89e48a53f6p-10, 0x1.24880485b11dp+0, -0x1.02dc27aee0746p-4, -0x1.b73ce6352161fp-3, -0x1.0cd5e3e317d16p-2, 0x1.8f224434b875ap-2, -0x1.770fce058233dp-3, 0x1.34f847ce948f6p-5, -0x1.6424e95f4ceffp-9 }, /* 14:61.079 */
#else
  /* the following degree-1 coefficient was modified to avoid an exceptional
     case for x=0x1.cb2452p-1 for rndd */
  { -0x1.78d89e48a53f6p-10, 0x1.24880485b11ep+0, -0x1.02dc27aee0746p-4, -0x1.b73ce6352161fp-3, -0x1.0cd5e3e317d16p-2, 0x1.8f224434b875ap-2, -0x1.770fce058233dp-3, 0x1.34f847ce948f6p-5, -0x1.6424e95f4ceffp-9 }, /* 14:61.079 */
#endif
  { -0x1.2f7854ff8ef7bp-9, 0x1.26728ecb8239bp+0, -0x1.754708b273ed9p-4, -0x1.3d3353afd28b9p-3, -0x1.5e3685a7ea032p-2, 0x1.d49cffc1f0a58p-2, -0x1.c13c3b9a3255cp-3, 0x1.8f7e777860d88p-5, -0x1.12c534d70236fp-8 }, /* 15:61.437 */
  { -0x1.b944b9611e298p-9, 0x1.2899ce7774285p+0, -0x1.ede8316bea9ecp-4, -0x1.88fd90bbfec3dp-4, -0x1.a9b894cb0b0d5p-2, 0x1.088b749b8fa83p-1, -0x1.fdcc1b631d593p-3, 0x1.d4d2f931a20e8p-5, -0x1.583c366b34ce1p-8 }, /* 16:61.052 */
  { -0x1.1d940c81edefdp-8, 0x1.2a83a2610a58cp+0, -0x1.2979882c6bbcfp-3, -0x1.94c3014e4d937p-5, -0x1.e1eab53d43df3p-2, 0x1.1dc197df00709p-1, -0x1.12eb4eb016b6ep-2, 0x1.0003483799f31p-4, -0x1.81078223d980fp-8 }, /* 17:63.231 */
  { -0x1.3dbb2492c1851p-8, 0x1.2b6a29990969fp+0, -0x1.401344f618329p-3, -0x1.e55a1341cc883p-6, -0x1.f89fb52db226p-2, 0x1.25e6a1c4e3a09p-1, -0x1.1a393d5339647p-2, 0x1.07802069f0f8p-4, -0x1.8e769784541edp-8 }, /* 18:68.227 */
  { -0x1.0d22acb495d76p-8, 0x1.2a25dc5205448p+0, -0x1.227bbb1d3b7b3p-3, -0x1.b8326c71d3216p-5, -0x1.dedef1e5247aep-2, 0x1.1d4de78710b86p-1, -0x1.130c7d11ccb41p-2, 0x1.00a7f96540989p-4, -0x1.83093e4d12b84p-8 }, /* 19:63.545 */
  { -0x1.25392d712ac6cp-10, 0x1.2544e485d02acp+0, -0x1.6b1ebf9c55d94p-4, -0x1.1bc70fc4dbab2p-3, -0x1.88443a50d4486p-2, 0x1.01ab5d47085d4p-1, -0x1.f9fff40a39f3ap-3, 0x1.d918785f330d6p-5, -0x1.62f0361180069p-8 }, /* 20:62.714 */
  { 0x1.604801d07d378p-8, 0x1.1b28516412dcep+0, 0x1.0dd8cac4977e3p-6, -0x1.319f4d9dda20ep-2, -0x1.d92dd63478e36p-3, 0x1.a497fe058e897p-2, -0x1.b1e95f53528f2p-3, 0x1.9a66ae1af0e2p-5, -0x1.3338cb3b2000ep-8 }, /* 21:62.336 */
#if 0
  { 0x1.127604309e4f3p-6, 0x1.0a3cc74c3631p+0, 0x1.79d5685eb39e7p-3, -0x1.15caed0fd5ae9p-1, -0x1.32bc48b25d63p-7, 0x1.20a314bbc5fa1p-2, -0x1.52040e741925ep-3, 0x1.4abeafeba6963p-5, -0x1.f2a2c0412e2dap-9 }, /* 22:62.165 */
#else
  /* the following degree-1 coefficient was modified to avoid an exceptional
     case for x=0x1.6b5c72p+0 for rndd */
  { 0x1.127604309e4f3p-6, 0x1.0a3cc74c3632p+0, 0x1.79d5685eb39e7p-3, -0x1.15caed0fd5ae9p-1, -0x1.32bc48b25d63p-7, 0x1.20a314bbc5fa1p-2, -0x1.52040e741925ep-3, 0x1.4abeafeba6963p-5, -0x1.f2a2c0412e2dap-9 }, /* 22:62.165 */
#endif
  { 0x1.18f58f056ca05p-5, 0x1.e2887dd4a0572p-1, 0x1.afe4dcce947cp-2, -0x1.beb0de5c874c1p-1, 0x1.1bf685ea40949p-2, 0x1.f56afb052e2e2p-4, -0x1.c0f175b3a0245p-4, 0x1.e0fe61914535p-6, -0x1.7516e7f765269p-9 }, /* 23:62.124 */
  { 0x1.e2b8cf6db29e5p-5, 0x1.9f536f1a0d7a8p-1, 0x1.74ac354e64f0dp-1, -0x1.47c7d93b9a5cbp+0, 0x1.3bfac77271869p-1, -0x1.e19af438b4764p-5, -0x1.9321056d55063p-5, 0x1.24839594cc40ep-6, -0x1.eed7a5a2fa6f5p-10 }, /* 24:62.181 */
  /* up from here, the polynomials directly approximates erfc(x) */
  { 0x1.bc6c1da1f3122p-6, 0x1.eb0fb82c4773ep-3, 0x1.147de5cedec6bp-1, -0x1.b160d3a717fffp-2, -0x1.2cdde602c6ae5p+0, 0x1.96dc3f94242f6p1, -0x1.ec40ee8d44b4fp+0, -0x1.d00a81297b0e2p2, 0x1.cf57faf9a669fp+4 }, /* 25:53.784 */
  { 0x1.612d893085125p-6, 0x1.b331a8769151p-3, 0x1.220ef8e80be6cp-1, -0x1.26af25b47bd64p-2, -0x1.9454d25e1fed1p+0, 0x1.ac4d7a786cc82p1, -0x1.6802a5ae670cbp-3, -0x1.a070f182510c2p3, 0x1.1898ee4f4c688p5 }, /* 26:55.908 */
  { 0x1.16b24cb8f8f92p-6, 0x1.7d8cbcbc7ffe6p-3, 0x1.29690fadbe3c4p-1, -0x1.0310514c774dap-3, -0x1.f4c027696dc76p+0, 0x1.9a3a1c3737ee6p1, 0x1.34b8898153aa6p1, -0x1.380ef06d5b43ap+4, 0x1.2267046080563p5 }, /* 27:55.432 */
 { 0x1.b4be201caa4b3p-7, 0x1.4b0138e6613bbp-3, 0x1.2aae1a57d88e9p-1, 0x1.b0ef6d98b2f4fp-5, -0x1.22d15f92dc6c2p1, 0x1.5911f7ab3b07ep1, 0x1.70094b9ade0e4p2, -0x1.9c89996c39558p+4, 0x1.d0e7311c940fcp+4 }, /* 28:53.401 */
  { 0x1.53c89d8bb3ddbp-7, 0x1.1c31d0d4b1a4dp-3, 0x1.2645c5107652p-1, 0x1.ee5355c04b3d6p-3, -0x1.3f9aee9735a1ap1, 0x1.cb14b408f265ep+0, 0x1.338cb41ae57dfp3, -0x1.e806d48a41958p+4, 0x1.5f9d5109e1b5bp3 }, /* 29:54.541 */
  { 0x1.0678442cc256ep-7, 0x1.e30f5786f4e75p-4, 0x1.1ccfdbab15adfp-1, 0x1.b81cc645cc929p-2, -0x1.4d9c3047a8a13p1, 0x1.0647c9f9039a2p-1, 0x1.b3e6e0768f7dbp3, -0x1.021e5f74d93afp5, -0x1.4d2a4d24a5b5fp+4 }, /* 30:52.695 */
  { 0x1.9299afa0246a5p-8, 0x1.9670ee7b43ef6p-4, 0x1.0f14a62ed1c8bp-1, 0x1.37e7a84e3dbf2p-1, -0x1.4aca290c23aadp1, -0x1.16a841a8f593ep+0, 0x1.14ff2eff7c49fp+4, -0x1.d8704e4c414e9p+4, -0x1.025c68fe40351p6 }, /* 31:53.581 */
  { 0x1.328f5ec350e66p-8, 0x1.529b9e8cf9964p-4, 0x1.fbe96dd36688cp-2, 0x1.8b0ae391d70dap-1, -0x1.366401b58b989p1, -0x1.747bfe375cf6ep1, 0x1.426889769d808p+4, -0x1.543826142ba3p+4, -0x1.d8ed78e8d563cp6 }, /* 32:53.115 */
  { 0x1.cf80d4afc3018p-9, 0x1.175aa070cc851p-4, 0x1.d4b2e997b62b7p-2, 0x1.d2221b9db3226p-1, -0x1.1103d5cba7a35p1, -0x1.3491849582dd2p2, 0x1.59f65b2efd05bp+4, -0x1.bbd054eb57971p2, -0x1.5db4242e0e538p7 }, /* 33:53.487 */
  { 0x1.5bde729a6b60fp-9, 0x1.c882fa9675f67p-5, 0x1.aa4ed0221cecfp-2, 0x1.056170a8a2699p+0, -0x1.b916ebf855dp+0, -0x1.ab0caf820282p2, 0x1.54d1ff8219f41p+4, 0x1.a3e1a8dd411a2p3, -0x1.c2de54f57e334p7 }, /* 34:55.648 */
  { 0x1.033197ec68c0ep-9, 0x1.71773aab52c14p-5, 0x1.7e65fd130faf6p-2, 0x1.19c1556c5c9cap+0, -0x1.37e229eb0e6cdp+0, -0x1.09efde3b64d94p3, 0x1.2ea4e35fa996p+4, 0x1.2d0b6123992dbp5, -0x1.0319b204c2cc2p+8 }, /* 35:53.261 */
  { 0x1.7f713f9cc9784p-10, 0x1.2834cd17fb1ddp-5, 0x1.52705455e81bdp-2, 0x1.25fa5f69fca86p+0, -0x1.4bce6e69f6ffap-1, -0x1.33063e4c109dap3, 0x1.ccbbbcb483c02p3, 0x1.0129c9a247c5fp6, -0x1.0b3d21ca17bbp+8 }, /* 36:54.251 */
  { 0x1.198fd6a0ee7bdp-10, 0x1.d685e500833dfp-6, 0x1.27a9e0b70347cp-2, 0x1.2a4a5fa0af3b3p+0, -0x1.7025cc4200b8cp-5, -0x1.4d2a7e2ff1a5p3, 0x1.fac338023faa8p2, 0x1.68f074bee96b1p6, -0x1.e14daa935cbf9p7 }, /* 37:53.579 */
  { 0x1.9a7c305336484p-11, 0x1.72433d8f1367bp-6, 0x1.fe1b02df0f7c5p-3, 0x1.27512c1728d7bp+0, 0x1.1da5bfd7572a3p-1, -0x1.55fa6c08092fbp3, -0x1.030535b4da786p-3, 0x1.c15ade3d04029p6, -0x1.56c5bd8985f98p7 }, /* 38:54.205 */
  { 0x1.29082600643fep-11, 0x1.20b2c6e9731cbp-6, 0x1.b2a8e9f696559p-3, 0x1.1df9ab303754p+0, 0x1.21244d7fe1bccp+0, -0x1.4c87997724b07p3, -0x1.24d54cd014e19p3, 0x1.fd9c51f33d531p6, -0x1.daa0bbfa1971fp5 }, /* 39:52.919 */
  { 0x1.aab859b20ac9fp-12, 0x1.be1cd4089b298p-7, 0x1.6df3a5ef15423p-3, 0x1.0f60bebe99b88p+0, 0x1.a49fdf0ff2dd7p+0, -0x1.31633f839ffeap3, -0x1.2721869b4f628p+4, 0x1.0907f2905af39p7, 0x1.5025cb827602cp6 }, /* 40:53.435 */
  { 0x1.30439c56dadf6p-12, 0x1.5591b9211ba66p-7, 0x1.3081d653b7cep-3, 0x1.f978f7d22a86ap-1, 0x1.09fc1a196e7a5p1, -0x1.067feda207dedp3, -0x1.b3e8cd293d28p+4, 0x1.f7ff2b8359782p6, 0x1.efa97a502f495p7 }, /* 41:54.306 */
  { 0x1.aeb4423e690e7p-13, 0x1.032e575abe004p-7, 0x1.f4f602381a048p-4, 0x1.ce8b53dfa17abp-1, 0x1.35d023daee4a7p1, -0x1.9de2f17f0175p2, -0x1.1681e37934102p5, 0x1.adeb165004e61p6, 0x1.a2f3fdbba9793p+8 }, /* 42:54.816 */
  { 0x1.2e984ed53e777p-13, 0x1.85d3c5ebc10cep-8, 0x1.9773b8078bcb7p-4, 0x1.a049e29cc16b8p-1, 0x1.54ec3bd600df2p1, -0x1.1d28980674704p2, -0x1.444aadbfc8e3dp5, 0x1.3662f87212bdbp6, 0x1.1e9b9f50f9aefp9 }, /* 43:54.901 */
  { 0x1.a609f7584d32cp-14, 0x1.2291819ebe589p-8, 0x1.47bd9ef3d00f5p-4, 0x1.70c9178f609ecp-1, 0x1.6749a7a037d3bp1, -0x1.269d377f05dfp1, -0x1.5fba5d7b56c07p5, 0x1.349b2ae16b67dp5, 0x1.5b07f35723e2fp9 }, /* 44:53.615 */
  { 0x1.2422ed95a3235p-14, 0x1.ad59f260bcf68p-9, 0x1.04c2e94b0f1e4p-4, 0x1.41cd6db5b0eebp-1, 0x1.6d9d4a8c40d26p1, -0x1.19d1f86e72c89p-3, -0x1.66f7c22ea0792p5, -0x1.a2ccc06f82187p2, 0x1.7c8c9e9a1d92cp9 }, /* 45:53.6 */
  { 0x1.916f7c5f2f764p-15, 0x1.3a6e560131667p-9, 0x1.9a80bc585d9d9p-5, 0x1.14c164c0e3933p-1, 0x1.692f95f4dfe5bp1, 0x1.ea5b96d823bedp+0, -0x1.59f3998dee4bap5, -0x1.af69dcab9a46p5, 0x1.7d17223a638cfp9 }, /* 46:55.045 */
  { 0x1.11c3bed8e716ap-15, 0x1.c886587231585p-10, 0x1.3fb5715d8b6f5p-5, 0x1.d566ef622b5e3p-2, 0x1.5baf462c67bb9p1, 0x1.e0ce85385be1ap1, -0x1.3a4cff1ed9031p5, -0x1.8d6e3aab6edffp6, 0x1.5c9499391b893p9 }, /* 47:54.447 */
  { 0x1.729df6503422ap-16, 0x1.488a06f179891p-10, 0x1.eccf0a6a32445p-6, 0x1.88b4fc4b1c41cp-2, 0x1.4703e278ea529p1, 0x1.53ca7116c20abp2, -0x1.0b14f37587f8bp5, -0x1.164e85751fa16p7, 0x1.1a3bc8f6aeeabp9 }, /* 48:54.552 */
  { 0x1.f1febf7a916aap-17, 0x1.d4c7eb5d14d66p-11, 0x1.77e8da17ad393p-6, 0x1.443d715bf56a1p-2, 0x1.2d2410e071eb4p1, 0x1.a1b58c24f7ef5p2, -0x1.a0b0c55aca677p+4, -0x1.541d55d1e2426p7, 0x1.7933edba910c7p+8 }, /* 49:54.14 */
  { 0x1.4c144d984e1b8p-17, 0x1.4b90805480918p-11, 0x1.1bd33e1a52406p-6, 0x1.084b9897f6e79p-2, 0x1.0ff29abe0662ep1, 0x1.d8e50b1325501p2, -0x1.1d602879ed1c8p+4, -0x1.7bb4c2dce78dp7, 0x1.3036274f0a557p7 }, /* 50:53.746 */
  { 0x1.b792bbc489b03p-18, 0x1.d100b7477a354p-12, 0x1.a84934bb0f10ap-7, 0x1.a98074b7da29ap-3, 0x1.e24798d3f57c1p+0, 0x1.f9b048d87b447p2, -0x1.2b1d1f24b6012p3, -0x1.8b03baa44a2a7p7, -0x1.7020a36651743p6 }, /* 51:53.116 */
  { 0x1.20c1303550f0dp-18, 0x1.434916b158777p-12, 0x1.39f8dba9f65a5p-7, 0x1.5258f7d1bfd58p-3, 0x1.a457629fe3d1fp+0, 0x1.02e087db3292ap3, -0x1.1daa4a995dc22p+0, -0x1.8214aa0bed683p7, -0x1.4b21b0c5fe1f6p+8 }, /* 52:52.393 */
  { 0x1.7885ce9f67cdap-19, 0x1.bdb095c9e7596p-13, 0x1.cc18d7996f084p-8, 0x1.09d5e95c263b6p-3, 0x1.6869798ac84ap+0, 0x1.ffbad08fab278p2, 0x1.99d36b1f936cdp2, -0x1.6320cc8100931p7, -0x1.0fe51ecc9e095p9 }, /* 53:52.972 */
  { 0x1.e749309831665p-20, 0x1.309ca8e2eb21ap-13, 0x1.4dd1ee648894cp-8, 0x1.9cd6b4494b37bp-4, 0x1.303b8593cb3e8p+0, 0x1.eadd7946dbf4bp2, 0x1.9bbb484fad72fp3, -0x1.322ae3f9cad23p7, -0x1.65531a1725a4p9 }, /* 54:53.066 */
  { 0x1.38f2e86f38216p-20, 0x1.9cdb8fa409689p-14, 0x1.dfb4feb49aa6fp-9, 0x1.3ce14001120c9p-4, 0x1.f9f6e95a7d738p-1, 0x1.caad81d86d7cap2, 0x1.20d80a2ba83f4p+4, -0x1.e84daa9aea209p6, -0x1.9f223ad746d9dp9 }, /* 55:53.829 */
  { 0x1.8ef2a9a18d857p-21, 0x1.156c7b5ba5935p-14, 0x1.555c7bc9c447ap-9, 0x1.e0f2afb58065ap-5, 0x1.9eae69fad68bep-1, 0x1.a2a7e93c7c0b8p2, 0x1.5dc981376a1a9p+4, -0x1.5d638fa546a58p6, -0x1.bb816842c2004p9 }, /* 56:54.404 */
  { 0x1.f8c0c2e2ce8dfp-22, 0x1.71b2aab0b9419p-15, 0x1.e131392be4a96p-10, 0x1.68ea7f05fc39ep-5, 0x1.4f22c6e318e81p-1, 0x1.7606faac5249p2, 0x1.84d78fdac6b9dp+4, -0x1.9c9edbde4b768p5, -0x1.b9dcd19779e93p9 }, /* 57:53.76 */
  { 0x1.3ce784b411931p-22, 0x1.e8875688eaeebp-16, 0x1.4ff020c786dbdp-10, 0x1.0bddc7f9ef1bbp-5, 0x1.0b301e4763bccp-1, 0x1.47990d599cc3bp2, 0x1.9790aa1f70819p+4, -0x1.1328c07966271p+4, -0x1.9d29dd729a579p9 }, /* 58:53.676 */
  { 0x1.8aee4cd06ec1cp-23, 0x1.40133c085a1f2p-16, 0x1.d0a5cc2283e9bp-11, 0x1.894dc9044d9ebp-6, 0x1.a46d187ecb7d5p-2, 0x1.19a9142e9bc62p2, 0x1.988b0ff6feb7ap+4, 0x1.bac51f8e3fea4p3, -0x1.6a240b32b2e8ap9 }, /* 59:52.511 */
  { 0x1.e87470e4f4248p-24, 0x1.9fe9718828e01p-17, 0x1.3e54bc5530ccap-11, 0x1.1da6a5919fb7p-6, 0x1.4687052fd7e3p-2, 0x1.dbed58e12b96bp1, 0x1.8afd8c2962ee6p+4, 0x1.40e52e37714a6p5, -0x1.2738e8a7fb5ap9 }, /* 60:51.912 */
  { 0x1.2bc82ab9d2304p-24, 0x1.0bf85f1e5a4b7p-17, 0x1.b02010cf219f1p-12, 0x1.9a8a4cc6ae0bdp-7, 0x1.f4d5219eac307p-3, 0x1.8b754796613e3p1, 0x1.726185fb40cbbp+4, 0x1.e67936e2b9245p5, -0x1.b645fd418187cp+8 }, /* 61:51.482 */
  { 0x1.6d3126d74b6cep-25, 0x1.566ec8066a5e9p-18, 0x1.2296d661f0127p-12, 0x1.23ee3a70a0285p-7, 0x1.7b5e7d0f54cf9p-3, 0x1.4368c71d39646p1, 0x1.5222eb5632468p+4, 0x1.2e9df27db0677p6, -0x1.18ebb3f6d8828p+8 }, /* 62:51.312 */
  { 0x1.b9823c51276e4p-26, 0x1.b1f49824bfd5dp-19, 0x1.833b46063b1fp-13, 0x1.9ae14ecc82c29p-8, 0x1.1be5a518bd142p-3, 0x1.0479af5382182p1, 0x1.2d63ee0f93088p+4, 0x1.535f71e65423ep6, -0x1.03508aca030dep7 }, /* 63:51.016 */
  { 0x1.08ddd13bd35e9p-26, 0x1.10b1488aeb4c5p-19, 0x1.ff4c680499687p-14, 0x1.1e2f637c32d55p-8, 0x1.a3de4e217eceap-4, 0x1.9d6f116ed258p+0, 0x1.06d4955a24d84p+4, 0x1.63b0ec472ae81p6, 0x1.9612e7b201494p2 }, /* 64:50.819 */
  { 0x1.3b62b6aafb0cap-27, 0x1.53e169a318926p-20, 0x1.4e7cfade6137cp-14, 0x1.8a9e48ecd1ba1p-9, 0x1.32dcf43f41c61p-4, 0x1.43748981802a9p+0, 0x1.c13bccbcfa9a5p3, 0x1.62b53dfda19b9p6, 0x1.e2ed14d3860cep6 }, /* 65:50.934 */
  { 0x1.74b179d1eba84p-28, 0x1.a4208fed956e7p-21, 0x1.b1ade4d2388d7p-15, 0x1.0d5484e2c4393p-9, 0x1.bb660382ed95ap-5, 0x1.f3260d7bc81e4p-1, 0x1.78ba6ae66f5e2p3, 0x1.541345355a3a8p6, 0x1.a4c4eb22e558p7 }, /* 66:50.785 */
  { 0x1.b512a1fb1d8ffp-29, 0x1.01856ce14231p-21, 0x1.169c10bd9c2c5p-15, 0x1.6bf8ac1381b05p-10, 0x1.3cb81fbc74f64p-5, 0x1.7bf8df3b811a5p-1, 0x1.36567e596617p3, 0x1.3b7ee78c5cb25p6, 0x1.1218c0f2c4022p+8 }, /* 67:51.094 */
  { 0x1.fcae93fb7323fp-30, 0x1.391aa4302f74bp-22, 0x1.62c3bfa8e678fp-16, 0x1.e6fff0edb894p-11, 0x1.bf6ac19d5ef1ep-6, 0x1.1d76cb7ceae26p-1, 0x1.f6b2869722092p2, 0x1.1c7d56e677d4cp6, 0x1.394e253954744p+8 }, /* 68:51.538 */
  { 0x1.25c354b26cb4ep-30, 0x1.798ed7dc940f8p-23, 0x1.bfb356ac63a44p-17, 0x1.429b1e2469343p-11, 0x1.388b2b5b5d32ep-6, 0x1.a76f2a35d1ab4p-2, 0x1.909881aabd638p2, 0x1.f441061f72dp5, 0x1.4aac4d5b500b3p+8 }, /* 69:52.875 */
  { 0x1.50b75c536f926p-31, 0x1.c38c19a8f1p-24, 0x1.17fa4f2cfd9e5p-17, 0x1.a73dff7df9504p-12, 0x1.afe74ebaeafdfp-7, 0x1.361b2c2196204p-2, 0x1.3a4bf4f6e4d71p2, 0x1.adde31ebf6d3fp5, 0x1.49f71c5aa81bdp+8 }, /* 70:52.309 */
  { 0x1.7f03b935e8e35p-32, 0x1.0bceb1efde5f1p-24, 0x1.5b131efaffa82p-18, 0x1.12f23e96d174bp-12, 0x1.2736688f3f0e6p-7, 0x1.c0a16f8f52444p-3, 0x1.e5d1c211cb2b4p1, 0x1.69abc71bb8d63p5, 0x1.3b44c0c9f1517p+8 }, /* 71:50.4 */
  { 0x1.b05cfe2e9942bp-33, 0x1.3b11da097f39ep-25, 0x1.aa73a99da282bp-19, 0x1.61c8650535e49p-13, 0x1.8f44bf21d19b2p-8, 0x1.409851e06225fp-3, 0x1.720c80022a7abp1, 0x1.2a5e859d65e8dp5, 0x1.22b97aa2b7ebbp+8 }, /* 72:49.494 */
  { 0x1.e45a9790460bp-34, 0x1.6fa579743ca7cp-26, 0x1.03af8cbd4d7d1p-19, 0x1.c2deda7d606a5p-14, 0x1.0b27ec38975c3p-8, 0x1.c4c0b0792b26bp-4, 0x1.15e913d842eccp1, 0x1.e344eb2a19723p+4, 0x1.0413f887101aap+8 }, /* 73:48.798 */
  { 0x1.0d3b35021d686p-34, 0x1.a97f9a3ff7987p-27, 0x1.397ea8883063fp-20, 0x1.1c91c30cebb05p-14, 0x1.61c8b98f2ffd5p-9, 0x1.3bf3ddbb4cac3p-4, 0x1.9bb8db8e2b146p+0, 0x1.80919f8febb9bp+4, 0x1.c50cfd87fa6c2p7 }, /* 74:48.181 */
  { 0x1.2906cb94eb3f6p-35, 0x1.e871781d7a5fep-28, 0x1.77250d289c57bp-21, 0x1.63d1b689372a6p-15, 0x1.cfa83d45a9421p-10, 0x1.b3e2ee19b582ep-5, 0x1.2ce9d5d6fb521p+0, 0x1.2cf242a2b9db5p+4, 0x1.813b90db98159p7 }, /* 75:47.697 */
  { 0x1.4531410823007p-36, 0x1.1611b68cd20d2p-28, 0x1.bd0178d3753bfp-22, 0x1.b8b9abdb1eb61p-16, 0x1.2cb62854a7fc4p-10, 0x1.29405541865c9p-5, 0x1.b21def51411fbp-1, 0x1.cf8247b9b25e1p3, 0x1.406cc637a58d1p7 }, /* 76:47.227 */
  { 0x1.61500f5293ed3p-37, 0x1.3a09029477d18p-29, 0x1.05a50a051d621p-22, 0x1.0e6499b11c577p-16, 0x1.8218678c6e63fp-11, 0x1.90dd1760c067fp-6, 0x1.35242feb2fcbap-1, 0x1.5f75dca60c82dp3, 0x1.05205e1641695p7 }, /* 77:46.793 */
  { 0x1.7cef42e9a6135p-38, 0x1.5fc644c4795cp-30, 0x1.310191a8c753fp-23, 0x1.48b1ba0fbb84ap-17, 0x1.eab8ba2b08a02p-12, 0x1.0b4b9478f0054p-6, 0x1.b2c50e74d6fep-2, 0x1.068a3e945b074p3, 0x1.a1863278364abp6 }, /* 78:46.397 */
#if 0
  { 0x1.97945aa1c9bd1p-39, 0x1.86daa4e5dace4p-31, 0x1.607b30e474b04p-24, 0x1.8bdd8c53d2646p-18, 0x1.34ba2c2b8d6eap-12, 0x1.608d3119b44acp-7, 0x1.2df5fb4cbf6e6p-2, 0x1.829481f6688e3p2, 0x1.47cd30cef0f82p6 }, /* 79:46.03 */
#else
  /* the following degree-0 coefficient was modified to avoid an exceptional
     case for x=0x1.3f16eep+2 for rndz and rndu */
  { 0x1.97945aa1c9c08p-39, 0x1.86daa4e5dace4p-31, 0x1.607b30e474b04p-24, 0x1.8bdd8c53d2646p-18, 0x1.34ba2c2b8d6eap-12, 0x1.608d3119b44acp-7, 0x1.2df5fb4cbf6e6p-2, 0x1.829481f6688e3p2, 0x1.47cd30cef0f82p6 }, /* 79:46.03 */
#endif
  { 0x1.b0c1a759f76b2p-40, 0x1.aec1eb77be187p-32, 0x1.93d5ccbdcff68p-25, 0x1.d85e3101b481fp-19, 0x1.8098a78d140e4p-13, 0x1.cbf3b2a468f6p-8, 0x1.9e5cc04f5e484p-3, 0x1.189ee6db25161p2, 0x1.f9e8efde44561p5 }, /* 80:45.68 */
  { 0x1.c7fa0c7e3ba14p-41, 0x1.d6e4a6dd5e317p-33, 0x1.cab1891bc2cfp-26, 0x1.173d9159359dbp-19, 0x1.da60f9d5a7696p-14, 0x1.28cf79650bc77p-8, 0x1.18e97089f90dp-3, 0x1.91d614113232ep1, 0x1.7ffefce857487p5 }, /* 81:45.348 */
  { 0x1.dcc4fabf32e32p-42, 0x1.fe9b58e0d002ap-34, 0x1.02449a53ae849p-26, 0x1.4720eda502349p-20, 0x1.21b0a80479a37p-14, 0x1.7afd8ba7ea808p-9, 0x1.7867cd0d9ea73p-4, 0x1.1bdc46a88eb2bp1, 0x1.1edce9df2730ep5 }, /* 82:45.029 */
  { 0x1.eeb27891d2a88p-43, 0x1.12994ee589d4ep-34, 0x1.205914b8149eap-27, 0x1.7bbd9cd50d80fp-21, 0x1.5e5ca114209e6p-15, 0x1.ded1f24d9240dp-10, 0x1.f283c15ec8044p-5, 0x1.8bcbc9ddb76ddp+0, 0x1.a6123fe557786p+4 }, /* 83:44.728 */
  { 0x1.fd5f08ad2b123p-44, 0x1.24f8172c04a89p-35, 0x1.3f2ee9fab0166p-28, 0x1.b4d13164231cp-22, 0x1.a3a2370babc1cp-16, 0x1.2b4f7e1a90e0cp-10, 0x1.465739accaf3ep-5, 0x1.10656628462e3p+0, 0x1.31eb1daa536f4p+4 }, /* 84:44.439 */
  { 0x1.043b9f1621f0ap-44, 0x1.360c4738438efp-36, 0x1.5e4e7f15d27b9p-29, 0x1.f1eeef4dfc6cp-23, 0x1.f1c218189555cp-17, 0x1.72517878c5f07p-11, 0x1.a66e886d605f2p-6, 0x1.72374cae01accp-1, 0x1.b517e6b47413dp3 }, /* 85:44.16 */
  { 0x1.07dd6833bb263p-45, 0x1.457a96843d717p-37, 0x1.7d3271cfafa14p-30, 0x1.193eea572a877p-23, 0x1.246268a5aade3p-17, 0x1.c57571a14765bp-12, 0x1.0e5a44de24adcp-6, 0x1.f0ef0dd9c2b83p-2, 0x1.33e3d002d8919p3 }, /* 86:43.89 */
  { 0x1.097f82fc03ecep-46, 0x1.52ed5773a6c9dp-38, 0x1.9b4afc2e8342bp-31, 0x1.3adc36ac26c3ap-24, 0x1.54384f83d8489p-18, 0x1.12cc6338d61e8p-12, 0x1.56388253289adp-7, 0x1.4972b83e7d7a4p-2, 0x1.abd52b12f264fp2 }, /* 87:43.63 */
  { 0x1.09182b326b092p-47, 0x1.5e178bbc8135fp-39, 0x1.b80217d57dadep-32, 0x1.5d5757a36eff5p-25, 0x1.882065d2cb2c1p-19, 0x1.49aedc100483cp-13, 0x1.ac74152cbee2bp-8, 0x1.af943fbd62cd1p-3, 0x1.2547806331a95p2 }, /* 88:43.38 */
  { 0x1.06a996198ee91p-48, 0x1.66b7c063c1935p-40, 0x1.d2c039fd6d995p-33, 0x1.802501f18a7b5p-26, 0x1.bfafae8d5c1b5p-20, 0x1.878c7a624ea7p-14, 0x1.094d1dd26bd4bp-8, 0x1.1756d00b6d11ep-3, 0x1.8cd1e19fc8c8dp1 }, /* 89:43.136 */
  { 0x1.0241de6c31c31p-49, 0x1.6c9a8b63754c1p-41, 0x1.eaf174825d044p-34, 0x1.a2a9c14d3f36dp-27, 0x1.fa50e41de4a3dp-21, 0x1.cc5fd2895f6b8p-15, 0x1.450682153ea36p-9, 0x1.65612d088a41p-4, 0x1.0902173b6f927p1 }, /* 90:42.899 */
#if 0
  { 0x1.f7f4f887518c1p-51, 0x1.6f9c89197edecp-42, 0x1.00055f77405d3p-34, 0x1.c43e1f00cb3ecp-28, 0x1.1ba251558d7b1p-21, 0x1.0bf5cb0bd41b3p-15, 0x1.89f5215dd061bp-10, 0x1.c3f295e8fb117p-5, 0x1.5d7e0273b68ap+0 }, /* 91:42.669 */
#else
  /* the following degree-0 coefficient was modified to avoid an exceptional
     case for x=0x1.6db654p+2 for rndz and rndu */
  { 0x1.f7f4f88751958p-51, 0x1.6f9c89197edecp-42, 0x1.00055f77405d3p-34, 0x1.c43e1f00cb3ecp-28, 0x1.1ba251558d7b1p-21, 0x1.0bf5cb0bd41b3p-15, 0x1.89f5215dd061bp-10, 0x1.c3f295e8fb117p-5, 0x1.5d7e0273b68ap+0 }, /* 91:42.669 */
#endif
  { 0x1.e7eea02e4e7eep-52, 0x1.6fabbdf67ac09p-43, 0x1.08c7923644c01p-35, 0x1.e433b02b148d1p-29, 0x1.3ad1ce30648cdp-22, 0x1.34d9f8f1a8debp-16, 0x1.d8787bfa83aaep-11, 0x1.1a82edfb3c715p-5, 0x1.c72f56ac5e436p-1 }, /* 92:42.445 */
  { 0x1.d4ca9b634e678p-53, 0x1.6cc8492559ec5p-44, 0x1.0f8a48e4743e2p-36, 0x1.00ed6c590c94p-29, 0x1.5a317a8fd4637p-23, 0x1.607d069541eb5p-17, 0x1.1859a3fd5933ep-11, 0x1.5d3654291475ep-6, 0x1.24cbaa86ac2a1p-1 }, /* 93:42.226 */
  { 0x1.bef1b1a127b53p-54, 0x1.67045e7e350d4p-45, 0x1.142400bd1a8abp-37, 0x1.0e448062e74bap-30, 0x1.792d60dc239aep-24, 0x1.8e5d1eb405316p-18, 0x1.493f6212dbb57p-12, 0x1.aad8574d4b926p-7, 0x1.74234437dac61p-2 }, /* 94:42.013 */
  { 0x1.a6d7d188310f9p-55, 0x1.5e83885cdb57ap-46, 0x1.167865829185bp-38, 0x1.19cf77acedd05p-31, 0x1.9727415ef307fp-25, 0x1.bdd6b57940418p-19, 0x1.7eafe08797fb9p-13, 0x1.01fca7a644182p-7, 0x1.d35b0493eb01bp-3 }, /* 95:41.805 */
};

/* assume |x0| >= 6, thus erfc(|x0|) < 2.16e-17 */
static float
erfcf_asympt (float x0)
{
  /* Reference: Abramowitz and Stegun, formulae 7.1.23 and 7.1.24:
     when x goes to infinity, sqrt(pi)*x*exp(x^2)*erfc(x) =
     1 + sum((-1)^k*(1*3*...*(2k-1))/(2x^2)^k, k=1..n)
     with error bounded in absolute value by the next term and of same sign. */
  double x = x0;
  double xx = x * x; /* no overflow nor underflow */
  static const double one_over_log2 = 0x1.71547652b82fep+0;
  xx *= one_over_log2;
  int k = xx;
  double r = xx - k;
  /* exp(x^2) ~ 2^k*2^r */
  /* minimax polynomial for 2^x over 0 <= x < 1, see exp2.sollya */
  static const double p[11] = { 0x1.0000000000001p+0, 0x1.62e42fefa3801p-1,
                                0x1.ebfbdff84064ep-3, 0x1.c6b08d6b3c355p-5,
                                0x1.3b2ab7a2083ap-7, 0x1.5d87e5a422438p-10,
                                0x1.430b5f0effbaep-13, 0x1.ff8689ef50997p-17,
                                0x1.655ce735731f7p-20, 0x1.9653ee727aa61p-24,
                                0x1.55fb387340127p-27 };
  double y = p[10];
  for (int i = 9; i >= 0; i--)
    y = p[i] + y * r;
  /* now y approximates 2^r */
  y = ldexp (y, k);
  /* now y approximates 2^k*2^r ~ exp(x^2) */
  y *= __builtin_fabs (x);
  static const double sqrt_pi = 0x1.c5bf891b4ef6bp+0;
  y *= sqrt_pi;
  /* y approximates exp(x^2)*x*sqrt(pi) */
  double z = 1.0 / __builtin_fabs (x);
  /* minimax polynomial for erfc(1/t)*exp(1/t^2)*1/t*sqrt(pi)), for
     1/10.0542 <= t <= 1/6, see erfc_asympt.sollya */
  static const double q[9] = { 0x1.fffffe09a380dp-1, 0x1.1d8395ea8e082p-18,
                               -0x1.0012123a9d313p-1, 0x1.56da878363a17p-9,
                               0x1.6f953e69a52ep-1, 0x1.0de98ea7feaabp-2,
                               -0x1.a99b5b5c063b6p1, 0x1.4463bb9082a49p2,
                               -0x1.5ec2a924f89dep1 };
  double num = q[8];
  for (int i = 7; i >= 0; i--)
    num = q[i] + z * num;
  /* num approximates erfc(x)*exp(x^2)*x*sqrt(pi) */
  y = num / y;
  return (x0 > 0) ? y : 2.0 - y;
}

float
erfcf (float x)
{
  /* deal with NaN here */

  double xx = (x >= 0) ? x : -x, y;

  if (xx > 0x1.41bbf6p3f)
    return (x > 0) ? 0x1p-149f * 0.5f : 2.0f - 0x1p-24f;

  /* exceptional cases */
  float h, l;
  if (x == -0x1.d93ec4p-17f) /* for rndn */
  {
    h = 0x1.00010ap+0f;
    l = 0x1.fffffep-25f;
    return h + l;
  }

  /* now xx <= 0x1.41bbf6p3 ~ 10.0542 */
  int i = SAMPLE * xx;
  if (i >= PSIZE)
    return erfcf_asympt (x);
  const double *p;
  if (i >= THRESHOLD) /* the polynomial approximates erfc(1/x) */
    {
      double x1 = (double) SAMPLE / (double) i;
      xx = 1.0 / xx - x1;
    }
  p = P[i];
  y = p[8];
  y = p[7] + y * xx;
  y = p[6] + y * xx;
  y = p[5] + y * xx;
  y = p[4] + y * xx;
  y = p[3] + y * xx;
  y = p[2] + y * xx;
  y = p[1] + y * xx;
  y = p[0] + y * xx;

  /* erfc(x) = 1 - erf(x), and erf(x) is approximated by sign(x)*y */
  if (i < THRESHOLD) /* p approximates erf(|x|) */
    y = (x > 0) ? 1.0 - y : 1.0 + y;
  else /* p approximates erfc(|x|) */
    y = (x > 0) ? y : 2.0 - y;
  return y;
}
